version: '3.8'

services:
  arslanchat:
    build: .
    container_name: arslanchat_app
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
